version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    networks:
      - virtualnet

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres:postgres
    env_file:
      - docker.env
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    networks:
      - virtualnet

networks:
  virtualnet:
    name: virtualnet
    driver: bridge
